---
kind: Deployment
apiVersion: apps/v1
metadata: 
  name: dqmsquare-mirror-server-testbed
  namespace: default
  labels:
    app: dqmsquare-mirror-server-testbed
spec:
  selector:
    matchLabels:
      app: dqmsquare-mirror-server-testbed
  replicas: 1
  template: # This is the pod template
    metadata:
      labels:
        app: dqmsquare-mirror-server-testbed
    spec:
      containers:
      - name: dqmsquare-mirror-server-testbed
        image: registry.cern.ch/cmsweb/dqmsquare_mirror:v1.1.0_pre12 #imagetag
        command: ["./dqmsquare_k8_wrapper.sh", "server"]
        args: []
        resources:
          requests:
            memory: "100Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "400m"
        volumeMounts:
          - mountPath: /cephfs/testbed
            name: dqmsquare-mirror-pvc-testbed
      volumes:
      - name: dqmsquare-mirror-pvc-testbed
        persistentVolumeClaim:
          claimName: dqmsquare-mirror-pvc-testbed
          readOnly: false
---
kind: Deployment
apiVersion: apps/v1
metadata: 
  name: dqmsquare-mirror-parser-testbed
  namespace: default
  labels:
    app: dqmsquare-mirror-parser-testbed
spec:
  selector:
    matchLabels:
      app: dqmsquare-mirror-parser-testbed
  replicas: 1
  template: # This is the pod template
    metadata:
      labels:
        app: dqmsquare-mirror-parser-testbed
    spec:
      containers:
      - name: dqmsquare-mirror-parser-testbed
        image: registry.cern.ch/cmsweb/dqmsquare_mirror:v1.1.0_pre12 #imagetag
        command: ["./dqmsquare_k8_wrapper.sh", "parser"]
        args: []
        resources:
          requests:
            memory: "100Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "400m"
        volumeMounts:
          - mountPath: /cephfs/testbed
            name: dqmsquare-mirror-pvc-testbed
      volumes:
      - name: dqmsquare-mirror-pvc-testbed
        persistentVolumeClaim:
          claimName: dqmsquare-mirror-pvc-testbed
          readOnly: false
---
kind: Deployment
apiVersion: apps/v1
metadata: 
  name: dqmsquare-mirror-robber-testbed
  namespace: default
  labels:
    app: dqmsquare-mirror-robber-testbed
spec:
  selector:
    matchLabels:
      app: dqmsquare-mirror-robber-testbed
  replicas: 1
  template: # This is the pod template
    metadata:
      labels:
        app: dqmsquare-mirror-robber-testbed
    spec:
      containers:
      - name: dqmsquare-mirror-robber-testbed
        image: registry.cern.ch/cmsweb/dqmsquare_mirror:v1.1.0_pre12 #imagetag
        command: ["./dqmsquare_k8_wrapper.sh", "parser"]
        args: []
        resources:
          requests:
            memory: "2Gi"
            cpu: "400m"
          limits:
            memory: "4Gi"
            cpu: "800m"
        volumeMounts:
          - mountPath: /cephfs/testbed
            name: dqmsquare-mirror-pvc-testbed
      volumes:
      - name: dqmsquare-mirror-pvc-testbed
        persistentVolumeClaim:
          claimName: dqmsquare-mirror-pvc-testbed
          readOnly: false
---
kind: Deployment
apiVersion: apps/v1
metadata: 
  name: dqmsquare-mirror-robber-oldruns-testbed
  namespace: default
  labels:
    app: dqmsquare-mirror-robber-oldruns-testbed
spec:
  selector:
    matchLabels:
      app: dqmsquare-mirror-robber-oldruns-testbed
  replicas: 1
  template: # This is the pod template
    metadata:
      labels:
        app: dqmsquare-mirror-robber-oldruns-testbed
    spec:
      containers:
      - name: dqmsquare-mirror-robber-oldruns-testbed
        image: registry.cern.ch/cmsweb/dqmsquare_mirror:v1.1.0_pre12 #imagetag
        command: ["./dqmsquare_k8_wrapper.sh", "robber_oldruns"]
        args: []
        resources:
          requests:
            memory: "2Gi"
            cpu: "400m"
          limits:
            memory: "3Gi"
            cpu: "800m"
        volumeMounts:
          - mountPath: /cephfs/testbed
            name: dqmsquare-mirror-pvc-testbed
      volumes:
      - name: dqmsquare-mirror-pvc-testbed
        persistentVolumeClaim:
          claimName: dqmsquare-mirror-pvc-testbed
          readOnly: false
