# Secrets + env vars to pass to the k8s pod
# This is the k8s equivalent of the local .env file.
apiVersion: v1
kind: Secret
metadata:
  name: dqmsecret
  namespace: dqm
type: Opaque
data:
  # Remember that, before applying this file with kubectl, 
  # you will need to base64-encode the values and replace them
  # with the encoded ones. E.g, "ENV: production" must 
  # be replaced with "ENV: cHJvZHVjdGlvbg=="
  # To encode it:
  #
  # echo -n production | base64
  #
  # Note the "-n" which prevents echo from printing
  # a new line character.
  ENV: production
  POSTGRES_HOST: postgres
  POSTGRES_PRODUCTION_DB_NAME: postgres_production
  POSTGRES_PLAYBACK_DB_NAME: postgres
  DQM_FFF_SECRET: CHANGEME
  DQM_CR_USERNAMES: CHANGEME
  GRABBER_DEBUG: False
  SERVER_DEBUG: False
  SERVER_FFF_MACHINE: bu-c2f11-13-01
  CMSWEB_FRONTEND_PROXY_URL: https://cmsweb-testbed.cern.ch/dqm/dqm-square-origin-rubu
  FFF_PRODUCTION_MACHINES: bu-c2f11-09-01;fu-c2f11-11-01;fu-c2f11-11-02;fu-c2f11-11-03;fu-c2f11-11-04
  FFF_PLAYBACK_MACHINES: bu-c2f11-13-01;fu-c2f11-15-01;fu-c2f11-15-02;fu-c2f11-15-03;fu-c2f11-15-04