# Secrets + env vars to pass to the k8s pod
apiVersion: v1
kind: Secret
metadata:
  name: dqmsecret
  namespace: dqm
type: Opaque
data:
  ENV: production
  POSTGRES_HOST: postgres
  POSTGRES_PRODUCTION_DB_NAME: postgres_production
  POSTGRES_PLAYBACK_DB_NAME: postgres
  DQM_FFF_SECRET: CHANGEME
  DQM_CR_USERNAMES: CHANGEME
  GRABBER_DEBUG: False
  SERVER_DEBUG: False
