---
kind: Deployment
apiVersion: apps/v1
metadata: 
  name: scripta
  namespace: default
  labels:
    app: scripta
spec:
  selector:
    matchLabels:
      app: scripta
  replicas: 2
  template: # This is the pod template
    metadata:
      labels:
        app: scripta
    spec:
      containers:
      - name: scripta
        image: pmandrik/scripta #imagetag
        resources:
          requests:
            memory: "100Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "400m"
