apiVersion: storage.k8s.io/v1beta1 # https://github.com/dmwm/CMSKubernetes/blob/master/kubernetes/cmsweb/storages/cephfs-storage-default.yaml
kind: StorageClass
metadata:
  name: default-share
  namespace: auth
provisioner: manila-provisioner
parameters:
  type: "Geneva CephFS Testing"
  zones: nova
  osSecretName: os-trustee
  osSecretNamespace: kube-system
  protocol: CEPHFS
  backend: csi-cephfs
  csi-driver: cephfs.csi.ceph.com
  osShareID: cec913f6-0016-4f59-9105-14d3abd4c607
  osShareAccessID: 6169ece6-78f6-4be2-9450-4f71788bdfc0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-cephfs-claim-preprod-default
  namespace: auth
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1G
  storageClassName: default-share
---
kind: Deployment
apiVersion: apps/v1
metadata: 
  name: scripta
  namespace: default
  labels:
    app: scripta
spec:
  selector:
    matchLabels:
      app: scripta
  replicas: 2
  template: # This is the pod template
    metadata:
      labels:
        app: scripta
    spec:
      containers:
      - name: scripta
        image: pmandrik/scripta #imagetag
        resources:
          requests:
            memory: "100Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "400m"
