---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: existing-volume
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1G
  csi:
    driver: cephfs.csi.ceph.com
    volumeHandle: cec913f6-0016-4f59-9105-14d3abd4c607
    nodeStageSecretRef:
      name: os-trustee
      namespace: kube-system
    nodePublishSecretRef:
      name: os-trustee
      namespace: kube-system
    volumeAttributes:
      shareID: cec913f6-0016-4f59-9105-14d3abd4c607
      shareAccessID: 6169ece6-78f6-4be2-9450-4f71788bdfc0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: existing-manila-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1G
  storageClassName: ""
  volumeName: existing-volume
---
kind: Deployment
apiVersion: apps/v1
metadata: 
  name: scripta
  namespace: default
  labels:
    app: scripta
spec:
  selector:
    matchLabels:
      app: scripta
  replicas: 2
  template: # This is the pod template
    metadata:
      labels:
        app: scripta
    spec:
      containers:
      - name: scripta
        image: pmandrik/scripta #imagetag
        resources:
          requests:
            memory: "100Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "400m"
        volumeMounts:
          - mountPath: /cephfs/testbed/confdb-logs
            name: mypvc
      volumes:
      - name: mypvc
        persistentVolumeClaim:
          claimName: logs-cephfs-claim-preprod-default
          readOnly: false


