---
kind: Deployment
apiVersion: apps/v1
metadata: 
  name: scripta
  namespace: default
  labels:
    app: scripta
spec:
  selector:
    matchLabels:
      app: scripta
  replicas: 2
  template: # This is the pod template
    metadata:
      labels:
        app: scripta
    spec:
      containers:
      - name: scripta
        image: pmandrik/scripta #imagetag
        resources:
          requests:
            memory: "100Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "400m"
        volumeMounts:
          - name: eos
            mountPath: /eos # The path inside the container will be /eos
            mountPropagation: HostToContainer
      volumes:
        - name: eos
          hostPath:
            path: /var/eos # /project/c/cmsweb/www/dqm/k8test
      securityContext:
        seLinuxOptions:
          type: "spc_t"



